eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://service-registry:8761/eureka/
  instance:
    hostname: service-registry
 
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
